setup.py, src/pycel/version.py
I am likely to do a bunch of work on pycel and would like to have it packaged up  so that it can easily be used in virtualenvs.
=> specify source directories

src/pycel/excelwrapper.py
get_rangednames function, returns numpy array containing for each defined name its VBA id, name and formula. numpy array has fields properly defined as 'id', 'formula' and 'names'.
WARNING: by default numpy array requires dtype declaration to specify character length (here 'S200', i.e. 200 characters)
TODO: automate detection of max string length to set up numpy array accordingly
TODO: discriminate between worksheet & workbook ranged names
=> Defined Names acquisition

src/pycel/excellib.py, src/pycel/excelutil.py, tests/excellib.py
This PR adds a bunch of Excel functions and corresponding unit tests:
- MATCH
- MOD
- ISNA
- COUNTIF
- COUNTIFS
- ROUND
- YEARFRAC
- DATE
- MID
- COUNT
- SUMIF
=> Additional Functions

src/pycel/excelcompiler.py, src/pycel/excelutil.py, tests/excelutil.py
This is useful when you need to create graphs from various non-adjacent cells.
=> Cell.make_cells() now also accepts a list of unrelated cells

CHANGES.rst, binder/requirements.txt, notebooks/example.ipynb, src/pycel/excelcompiler.py, src/pycel/excellib.py, src/pycel/excelutil.py, src/pycel/version.py, test-requirements.txt, tests/conftest.py, tests/test_excelcompiler.py, tests/test_excellib.py, tests/test_excelutil.py
- Implement AVERAGEIFS()
- Take Iterative Calc Parameter defaults from workbook
Fixes #60, Binder Notebook Example not Working
=> 1.0b15 (2019-06-30)

src/pycel/lib/logical.py, tests/lib/test_logical.py
=> Implemented IFS()

setup.py, src/pycel/lib/date_time.py, tests/lib/test_date_time.py
=> Implemented DATEVALUE()

CHANGES.rst, binder/requirements.txt, src/pycel/addin.py, src/pycel/excelcompiler.py, src/pycel/excelformula.py, src/pycel/excellib.py, src/pycel/excelutil.py, src/pycel/excelwrapper.py, src/pycel/lib/binary.py, src/pycel/lib/date_time.py, src/pycel/lib/function_info.py, src/pycel/lib/logical.py, src/pycel/lib/text.py, src/pycel/version.py, test-requirements.txt, tests/conftest.py, tests/lib/test_binary.py, tests/lib/test_date_time.py, tests/lib/test_function_helpers.py, tests/lib/test_function_info.py, tests/lib/test_logical.py, tests/lib/test_text.py, tests/test_excelcompiler.py, tests/test_excelformula.py, tests/test_excellib.py, tests/test_excelutil.py, tests/test_excelwrapper.py, tests/test_package.py, tox.ini
Changes
-------
* Add Formula Support for Multi Area Ranges from defined names
* Allow ExcelCompiler init from openpyxl workbook
* Implement LOWER(), REPLACE(), TRIM() & UPPER()
* Implement ISERR()
* Reorganized time, time utils and text functions
* Add excelutil.AddressMultiAreaRange.
* Add abs_coordinate() property to AddressRange and AddressCell
* Cleanup import statements
Fixes
-----
* Resolved tox version issue on travis
* Fix defined names with Multi Area Range
* Fix DATEVALUE()
=> 1.0b17 (2019-09-02)

CHANGES.rst, src/pycel/excelcompiler.py, src/pycel/excelformula.py, src/pycel/excellib.py, src/pycel/excelutil.py, src/pycel/excelwrapper.py, src/pycel/lib/function_helpers.py, src/pycel/lib/logical.py, src/pycel/lib/lookup.py, src/pycel/version.py, tests/conftest.py, tests/lib/test_function_helpers.py, tests/lib/test_logical.py, tests/lib/test_lookup.py, tests/test_excelformula.py, tests/test_excellib.py, tests/test_excelutil.py, tests/test_excelwrapper.py
1.0b21 (2019-10-13)
===================
Changes
-------
* Speed up compile
* Implement defined names in multicolon ranges
* Tokenize ':' when adjoining functions as infix operator
* Various changes in prep to improve references, including
* Add reference expansion to function helpers
* Add sheet to indirect() and ref_param=0 to offset()
* Implement is_address() helper
* Implement intersection and union for AddressCell
Fixes
-----
* Fix #77, empty arg in IFERROR()
* Fix #78, None compare and cleanup error handling for various IFS() funcs
=> 1.0b21 (2019-10-13)

src/pycel/excelutil.py, tests/test_excelformula.py
This is a fix proposal for the issue described by #109 
- [x ] closes #109
- [x ] tests added: 1
Added test for failing test case
=> String concatenation issue 

CHANGES.rst, src/pycel/excelutil.py, src/pycel/version.py, tests/test_excelutil.py
=> Remove redundant references from rectangular intervals

CHANGES.rst, README.rst, src/pycel/excelcompiler.py, src/pycel/lib/function_helpers.py, src/pycel/lib/lookup.py, src/pycel/lib/text.py, tests/lib/test_lookup.py, tests/test_excelcompiler.py, tests/test_excellib.py
=> Fix MID() and REPLACE() and LEN() in a CSE context & Fix INDEX() error handling

CHANGES.rst, src/pycel/excelformula.py, tests/test_excelformula.py
=> Fix #86, tokenize.TokenError: ('EOF in multi-line statement',

CHANGES.rst, src/pycel/excelcompiler.py, tests/test_excelcompiler.py
=> Allowing plugins to be passed to the deserialization function `from_file`

src/pycel/lib/text.py, tests/lib/test_text.py
=> Add function TEXT #101

CHANGES.rst, README.rst, setup.py, src/pycel/version.py
Added
-----
* Added CHOOSE() function
* Added FORECAST() function
* Added INTERCEPT() function
* Added IFNA() function
* Added ISBLANK() function
* Added ISLOGICAL() function
* Added ISNONTEXT() function
* Added N() function
* Added NA() function
* Added SLOPE() function
* Added SUBSTITUTE() function
* Added TEXT() function  (Thanks, Luckykarter)
* Added TREND() function
* Added Reference Form for INDEX()
* Added str_params to excel_helper()
* Added ExcelCompiler.validate_serialized()
Changed
-------
* Improve LINEST() compatibilty w/ Excel
* Improve TEXT() compatibilty w/ Excel
* Improve error and number handling in some Text functions
* Improve IFS() to support array context
* Missing references from INDIRECT() and OFFSET() resolve more often
Fixed
-----
* Fix #111, Incorrect …
=> 1.0b27 (2021-07-10)

.travis.yml, CHANGES.rst, setup.py
=> Add support for networkx 2.6

CHANGES.rst, src/pycel/excelwrapper.py, src/pycel/version.py
* Add support for openpyxl >= 3.0.8,
=> 1.0b29 (2021-09-13)

src/pycel/lib/text.py, tests/lib/test_text.py
Add support for 'exact' command and test_text.py\test_exact() test.
=> Add support for 'exact' command.

src/pycel/excelcompiler.py
Reverts dgorissen/pycel#146 which breaks CI (e.g., https://app.travis-ci.com/github/dgorissen/pycel/jobs/568857575)
=> Revert "Update excelcompiler.py"
